# Generated by Django 4.0.3 on 2023-02-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_conference_temp_alter_conference_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='lat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='lon',
            field=models.TextField(null=True),
        ),
    ]
