FROM python:3

#these 2 lines install CRON
RUN apt-get update
RUN apt-get install cron -y


ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# ADD THESE TWO LINES TO SET UP ROOT CRONTAB
RUN touch /var/spool/cron/crontabs/root
RUN crontab -l

#the command line chnaged to add crontabs and start service
CMD python manage.py crontab add && service cron start && python manage.py runserver "0.0.0.0:8001"
